#! /bin/bash

echo "Current OpenFOAM version is $WM_PROJECT_VERSION."

versionFile=versionRules/foamVersio4wmles.H

versionRules/makeFoamVersionHeader.py $WM_PROJECT_VERSION >$versionFile.tmp


if [ -e $versionFile ]; then                                                    
    nrDiff=$(diff $versionFile.tmp $versionFile | wc -l | tr -d " ")            
    if [[ $nrDiff > 0 ]]; then                                                  
    echo "$versionFile changed"                                                 
    mv $versionFile.tmp $versionFile                                            
    else                                                                        
    # Make sure that not a complete recompilation is triggered                  
    echo "No change to $versionFile"                                            
    rm $versionFile.tmp                                                         
    fi                                                                          
else                                                                            
    echo "No $versionFile. Generating!"                                           
    mv $versionFile.tmp $versionFile                                            
fi                                          

# Ensure consistent definition of OPENFOAM_COM without relying anything else.   
# This may be available from the regular wmake rules, but use our own convention
#sed -ne 's/.*SWAK_IS_COM \([0-9][0-9]*\)/OPENFOAM_COM=\1/p' < $versionFile > rules/foamVersion
                                                                                
echo                                                                            
echo "Please include the output above when reporting a problem in the compilation. It helps diagnosing the problem    "
echo                                                                            

wmake 
