#!/bin/sh
#-------------------------------------------------------------------------------
# Copyright (C) 2023 Timofey Mukha
# SPDX-License-Identifier: (GPL-3.0-or-later)
#
# Description
#     Simplified script for generating version rules
#     similar to swak4foam definitions but without a python dependency.
#     Currently restricted to OpenFOAM.com variants.
#
# Environment
#     WM_PROJECT_DIR
#         The OpenFOAM project directory name
#     WM_PROJECT_VERSION
#         The project version
#
#-------------------------------------------------------------------------------
unset api patch

[ -d "${WM_PROJECT_DIR:-/dev/null}" ] || {
    echo "Invalid WM_PROJECT_DIR   ${WM_PROJECT_DIR:-[]}" 1>&2
    exit 2
}

if [ -d "$WM_PROJECT_DIR/META-INFO" ]
then
    # openfoam.com
    # - simply use foamEtcFile to extract api,patch information

    api="$("$WM_PROJECT_DIR"/bin/foamEtcFile -show-api)"
    patch="$("$WM_PROJECT_DIR"/bin/foamEtcFile -show-patch)"

    echo "OpenFOAM (com) - api=$api patch=$patch" 1>&2

    cat << VERSION_HEADER
// OpenFOAM versions information
// generated by the Allwmake-script of the libWallModelledLES-distro
#ifndef foamVersion4wmles_H
#define foamVersion4wmles_H

#define FOAM_VERSION4WMLES_FORK  com  /* unused */
#define FOAM_VERSION4WMLES_MAJOR $api
#define FOAM_VERSION4WMLES_MINOR 0
#define FOAM_VERSION4WMLES_PATCH 0
#define FOAM_VERSION4WMLES_PATCH_NUM 0

#define FOAM_VERSION4WMLES_IS_COM $api
#undef  FOAM_VERSION4WMLES_IS_ORG
#undef  FOAM_VERSION4WMLES_IS_EXTEND

// OPENFOAM_COM is the release date (YYMM) as an integer
#ifndef OPENFOAM_COM
# define OPENFOAM_COM $api
#endif

#endif  /* foamVersion4wmles_H */
VERSION_HEADER

else
    echo "Not an OpenFOAM.com version - revert to parsing version number" 1>&2
    exit 1
fi

exit 0

#-------------------------------------------------------------------------------
